CREATE TABLE IF NOT EXISTS `characters` (
	`account_name`            VARCHAR(45)             DEFAULT NULL,
	`obj_Id`                  DECIMAL(11, 0) NOT NULL DEFAULT 0,
	`char_name`               VARCHAR(35)    NOT NULL,
	`level`                   DECIMAL(11, 0)          DEFAULT NULL,
	`maxHp`                   DECIMAL(11, 0)          DEFAULT NULL,
	`curHp`                   DECIMAL(18, 0)          DEFAULT NULL,
	`maxCp`                   DECIMAL(11, 0)          DEFAULT NULL,
	`curCp`                   DECIMAL(18, 0)          DEFAULT NULL,
	`maxMp`                   DECIMAL(11, 0)          DEFAULT NULL,
	`curMp`                   DECIMAL(18, 0)          DEFAULT NULL,
	`acc`                     DECIMAL(11, 0)          DEFAULT NULL,
	`crit`                    DECIMAL(10, 0)          DEFAULT NULL,
	`evasion`                 DECIMAL(11, 0)          DEFAULT NULL,
	`mAtk`                    DECIMAL(11, 0)          DEFAULT NULL,
	`mDef`                    DECIMAL(11, 0)          DEFAULT NULL,
	`mSpd`                    DECIMAL(11, 0)          DEFAULT NULL,
	`pAtk`                    DECIMAL(11, 0)          DEFAULT NULL,
	`pDef`                    DECIMAL(11, 0)          DEFAULT NULL,
	`pSpd`                    DECIMAL(11, 0)          DEFAULT NULL,
	`runSpd`                  DECIMAL(11, 0)          DEFAULT NULL,
	`walkSpd`                 DECIMAL(11, 0)          DEFAULT NULL,
	`str`                     DECIMAL(11, 0)          DEFAULT NULL,
	`con`                     DECIMAL(11, 0)          DEFAULT NULL,
	`dex`                     DECIMAL(11, 0)          DEFAULT NULL,
	`_int`                    DECIMAL(11, 0)          DEFAULT NULL,
	`men`                     DECIMAL(11, 0)          DEFAULT NULL,
	`wit`                     DECIMAL(11, 0)          DEFAULT NULL,
	`face`                    DECIMAL(11, 0)          DEFAULT NULL,
	`hairStyle`               DECIMAL(11, 0)          DEFAULT NULL,
	`hairColor`               DECIMAL(11, 0)          DEFAULT NULL,
	`sex`                     DECIMAL(11, 0)          DEFAULT NULL,
	`heading`                 DECIMAL(11, 0)          DEFAULT NULL,
	`x`                       DECIMAL(11, 0)          DEFAULT NULL,
	`y`                       DECIMAL(11, 0)          DEFAULT NULL,
	`z`                       DECIMAL(11, 0)          DEFAULT NULL,
	`movement_multiplier`     DECIMAL(9, 8)           DEFAULT NULL,
	`attack_speed_multiplier` DECIMAL(10, 9)          DEFAULT NULL,
	`colRad`                  DECIMAL(10, 3)          DEFAULT NULL,
	`colHeight`               DECIMAL(10, 3)          DEFAULT NULL,
	`exp`                     DECIMAL(11, 0)          DEFAULT NULL,
	`sp`                      DECIMAL(11, 0)          DEFAULT NULL,
	`karma`                   DECIMAL(11, 0)          DEFAULT NULL,
	`pvpkills`                DECIMAL(11, 0)          DEFAULT NULL,
	`pkkills`                 DECIMAL(11, 0)          DEFAULT NULL,
	`clanid`                  DECIMAL(11, 0)          DEFAULT NULL,
	`maxload`                 DECIMAL(11, 0)          DEFAULT NULL,
	`race`                    DECIMAL(11, 0)          DEFAULT NULL,
	`classid`                 DECIMAL(11, 0)          DEFAULT NULL,
	`base_class`              INT(2)         NOT NULL DEFAULT 0,
	`deletetime`              DECIMAL(20, 0) NOT NULL DEFAULT 0,
	`cancraft`                DECIMAL(11, 0)          DEFAULT NULL,
	`title`                   VARCHAR(16)             DEFAULT NULL,
	`allyId`                  DECIMAL(11, 0)          DEFAULT NULL,
	`rec_have`                INT(3)         NOT NULL DEFAULT 0,
	`rec_left`                INT(3)         NOT NULL DEFAULT 0,
	`accesslevel`             DECIMAL(4, 0)           DEFAULT NULL,
	`online`                  DECIMAL(1, 0)           DEFAULT NULL,
	`onlinetime`              DECIMAL(20, 0) NOT NULL DEFAULT 0,
	`char_slot`               DECIMAL(1)              DEFAULT NULL,
	`newbie`                  DECIMAL(1, 0)           DEFAULT 1,
	`lastAccess`              DECIMAL(20, 0)          DEFAULT NULL,
	`clan_privs`              INT                     DEFAULT 0,
	`wantspeace`              DECIMAL(1, 0)           DEFAULT 0,
	`deleteclan`              DECIMAL(20, 0) NOT NULL DEFAULT 0,
	`isin7sdungeon`           DECIMAL(1, 0)  NOT NULL DEFAULT 0,
	`in_jail`                 DECIMAL(1, 0)           DEFAULT 0,
	`jail_timer`              DECIMAL(20, 0)          DEFAULT 0,
	PRIMARY KEY (`obj_Id`),
	KEY `clanid` (`clanid`)
);
