CREATE TABLE IF NOT EXISTS `pets` (
	`item_obj_id` DECIMAL(11) NOT NULL DEFAULT 0,
	`objId`       DECIMAL(11),
	`name`        VARCHAR(16),
	`level`       DECIMAL(11),
	`maxHp`       DECIMAL(11),
	`curHp`       DECIMAL(18, 0),
	`maxMp`       DECIMAL(11),
	`curMp`       DECIMAL(18, 0),
	`acc`         DECIMAL(11),
	`crit`        DECIMAL(11),
	`evasion`     DECIMAL(11),
	`mAtk`        DECIMAL(11),
	`mDef`        DECIMAL(11),
	`mSpd`        DECIMAL(11),
	`pAtk`        DECIMAL(11),
	`pDef`        DECIMAL(11),
	`pSpd`        DECIMAL(11),
	`str`         DECIMAL(11),
	`con`         DECIMAL(11),
	`dex`         DECIMAL(11),
	`_int`        DECIMAL(11),
	`men`         DECIMAL(11),
	`wit`         DECIMAL(11),
	`exp`         DECIMAL(11),
	`sp`          DECIMAL(11),
	`karma`       DECIMAL(11),
	`pkkills`     DECIMAL(11),
	`maxload`     DECIMAL(11),
	`fed`         DECIMAL(11),
	`max_fed`     DECIMAL(11),
	PRIMARY KEY (`item_obj_id`)
);
